// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATeRT0vfa5IVrruKXrhKuv10H_lLgxNzI',
    appId: '1:186326400243:web:d000fa2535a5eed1094b86',
    messagingSenderId: '186326400243',
    projectId: 'patronus-2680d',
    authDomain: 'patronus-2680d.firebaseapp.com',
    storageBucket: 'patronus-2680d.appspot.com',
    measurementId: 'G-DJWZ1TKF2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXdkARO3eUcrU_fg8n5gVy3x4lVDRzYc',
    appId: '1:186326400243:android:f4ea8f839cbfcb8c094b86',
    messagingSenderId: '186326400243',
    projectId: 'patronus-2680d',
    storageBucket: 'patronus-2680d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUblSFY7mbgfGBzui4-n6yE7zZlgHlj1w',
    appId: '1:186326400243:ios:b7a65bff128a32f1094b86',
    messagingSenderId: '186326400243',
    projectId: 'patronus-2680d',
    storageBucket: 'patronus-2680d.appspot.com',
    iosBundleId: 'com.example.patronus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUblSFY7mbgfGBzui4-n6yE7zZlgHlj1w',
    appId: '1:186326400243:ios:b7a65bff128a32f1094b86',
    messagingSenderId: '186326400243',
    projectId: 'patronus-2680d',
    storageBucket: 'patronus-2680d.appspot.com',
    iosBundleId: 'com.example.patronus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATeRT0vfa5IVrruKXrhKuv10H_lLgxNzI',
    appId: '1:186326400243:web:cfcc1437ddfb6aa9094b86',
    messagingSenderId: '186326400243',
    projectId: 'patronus-2680d',
    authDomain: 'patronus-2680d.firebaseapp.com',
    storageBucket: 'patronus-2680d.appspot.com',
    measurementId: 'G-N4WQPS6T7S',
  );

}